mysql:
  dns: root:root@tcp(127.0.0.1:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local
  
redis:
  addr: "192.168.31.85:6379"
  password: ""
  DB: 1
  poolSize: 30
  minIdleConn: 30

timeout:
  DelayHeartbeat: 10   #延迟心跳时间  单位秒
  HeartbeatHz: 60   #每隔多少秒心跳时间   
  HeartbeatMaxTime: 18000  #最大心跳时间  ，超过此就下线 
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

port:
  server: ":8080"
  udp: 3000
